### ISSUE TITLE
Problems with stable of Oxygen-Merchants Mod

### ISSUE THREAD

**Issue by Titoo8899** [AustereTony-MCMods/Oxygen-Merchants#1]
Hi,
your mod work good but it give Problems with the stable of your mod. I have testet your newest Shop create mod and have found a performance Problem when we config all thinks. But then you to fast click the configs and will edit thinks then can to 50/50 % the game crash. Please make a performance Update to your mod with more stable of the edit area of shops edit.

**Comment by Titoo8899** [comment]
Hi,
have testet the Performance with the second update and the stable of the mod is only to 75% okay the last 25% was not good. Hope you can make a performance and stable update in the future.

**Comment by AustereTony-MCMods** [comment]
Fixed in 0.8.0b.
