### ISSUE TITLE
[Feature Request] Assign Profile Globally

### ISSUE THREAD

**Issue by Sixdd6** [AustereTony-MCMods/Oxygen-Merchants#4]
I'm assuming from the docs that this assigns a profile to a specific entity instance. What I would like is to be able to assign a profile/profiles to all of an entity globally. My thinking is that I'd like to replace villager trading with this system so that all villagers of a specific profession can be assigned a specific profile or set of profiles.

**Comment by AustereTony-MCMods** [comment]
Due to project concept changes such feature will not be implemented. I'm sorry.
