### ISSUE TITLE
[1.12.2-0.9.1] Creating a Merchant and editing the "Selling" will crash the client.

### ISSUE THREAD

**Issue by LeDemmers** [AustereTony-MCMods/Oxygen-Merchants#5]
https://paste.dimdev.org/zezohipoji.mccrash

To recreate, assign entity with profile. New Offer, make it buyable.
Go back to menu, right click on offer, and add sellable option, click confirm. Game crashes.

**Comment by AustereTony-MCMods** [comment]
Hello.
This problem should be fixed in ver. 0.9.2b. Please check it and close the issue.

**Comment by AustereTony-MCMods** [comment]
Consider it closed.
